spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fouille?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
